### ISSUE TITLE
Can't serialize structs that contain `::Type{T}` fields

### ISSUE THREAD

**Issue by ericphanson** [JuliaData/Arrow.jl#140] opened 2021-03-02 16:22 UTC
```julia
struct MyObject{T}
    field::Type{T}
end
MyObject(Int16)
Arrow.ArrowTypes.registertype!(MyObject, MyObject)
tbl = (; obj = [MyObject(Int16), MyObject(Int16)])
Arrow.write("test.arrow", tbl)
```
yields
```julia
ERROR: ArgumentError: type does not have a definite number of fields
Stacktrace:
 [1] fieldcount at ./reflection.jl:725 [inlined]
 [2] arrowvector(::Arrow.ArrowTypes.StructType, ::Arrow.ToStruct{Type{Int16},1,Array{MyObject{Int16},1}}, ::Int64, ::Int64, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{5,Symbol},NamedTuple{(:dictencode, :compression, :largelists, :denseunions, :dictencodenested),Tuple{Bool,Nothing,Bool,Bool,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:89
 [3] arrowvector(::Type{Type{Int16}}, ::Arrow.ToStruct{Type{Int16},1,Array{MyObject{Int16},1}}, ::Int64, ::Int64, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{5,Symbol},NamedTuple{(:dictencode, :compression, :largelists, :denseunions, :dictencodenested),Tuple{Bool,Nothing,Bool,Bool,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:90
 [4] arrowvector(::Arrow.ToStruct{Type{Int16},1,Array{MyObject{Int16},1}}, ::Int64, ::Int64, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; dictencoding::Bool, dictencode::Bool, kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{4,Symbol},NamedTuple{(:compression, :largelists, :denseunions, :dictencodenested),Tuple{Nothing,Bool,Bool,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:58
 [5] (::Arrow.var"#45#46"{Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{5,Symbol},NamedTuple{(:dictencode, :compression, :largelists, :denseunions, :dictencodenested),Tuple{Bool,Nothing,Bool,Bool,Bool}}},Array{MyObject{Int16},1},Int64,Int64,Dict{Int64,Any},Array{Arrow.DictEncoding,1}})(::Int64) at ./none:0
 [6] iterate at ./generator.jl:47 [inlined]
 [7] collect(::Base.Generator{UnitRange{Int64},Arrow.var"#45#46"{Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{5,Symbol},NamedTuple{(:dictencode, :compression, :largelists, :denseunions, :dictencodenested),Tuple{Bool,Nothing,Bool,Bool,Bool}}},Array{MyObject{Int16},1},Int64,Int64,Dict{Int64,Any},Array{Arrow.DictEncoding,1}}}) at ./array.jl:686
 [8] _totuple at ./tuple.jl:258 [inlined]
 [9] Tuple at ./tuple.jl:230 [inlined]
 [10] arrowvector(::Arrow.ArrowTypes.StructType, ::Array{MyObject{Int16},1}, ::Int64, ::Int64, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{5,Symbol},NamedTuple{(:dictencode, :compression, :largelists, :denseunions, :dictencodenested),Tuple{Bool,Nothing,Bool,Bool,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:89
 [11] arrowvector(::Type{MyObject{Int16}}, ::Array{MyObject{Int16},1}, ::Int64, ::Int64, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{5,Symbol},NamedTuple{(:dictencode, :compression, :largelists, :denseunions, :dictencodenested),Tuple{Bool,Nothing,Bool,Bool,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:90
 [12] arrowvector(::Array{MyObject{Int16},1}, ::Int64, ::Int64, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; dictencoding::Bool, dictencode::Bool, kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},NTuple{4,Symbol},NamedTuple{(:compression, :largelists, :denseunions, :dictencodenested),Tuple{Nothing,Bool,Bool,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:58
 [13] toarrowvector(::Array{MyObject{Int16},1}, ::Int64, ::Dict{Int64,Any}, ::Array{Arrow.DictEncoding,1}, ::Nothing; compression::Nothing, kw::Base.Iterators.Pairs{Symbol,Bool,NTuple{4,Symbol},NamedTuple{(:largelists, :denseunions, :dictencode, :dictencodenested),NTuple{4,Bool}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:36
 [14] (::Arrow.var"#109#110"{Dict{Int64,Any},Bool,Nothing,Bool,Bool,Bool,Array{Any,1},Array{Type,1},Array{Arrow.DictEncoding,1}})(::Array{MyObject{Int16},1}, ::Int64, ::Symbol) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:202
 [15] eachcolumn at /home/ec2-user/.julia/packages/Tables/8FVkV/src/utils.jl:70 [inlined]
 [16] toarrowtable(::NamedTuple{(:obj,),Tuple{Array{MyObject{Int16},1}}}, ::Dict{Int64,Any}, ::Bool, ::Nothing, ::Bool, ::Bool, ::Bool) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:201
 [17] macro expansion at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:111 [inlined]
 [18] macro expansion at ./task.jl:332 [inlined]
 [19] write(::IOStream, ::NamedTuple{(:obj,),Tuple{Array{MyObject{Int16},1}}}, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::Bool, ::Int64) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:108
 [20] #100 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:77 [inlined]
 [21] open(::Arrow.var"#100#101"{Bool,Nothing,Bool,Bool,Bool,Int64,NamedTuple{(:obj,),Tuple{Array{MyObject{Int16},1}}}}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:325
 [22] open at ./io.jl:323 [inlined]
 [23] #write#99 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:76 [inlined]
 [24] write(::String, ::NamedTuple{(:obj,),Tuple{Array{MyObject{Int16},1}}}) at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:76
 [25] top-level scope at REPL[6]:1
```

**Comment by ericphanson** [comment] 2021-03-02 16:28
I also tried not annotating with `::Type` and got an "unreachable reached" on Julia 1.5.3:
```julia
julia> struct MyObject2{TT}
           field::TT
       end

julia> MyObject2(Int16)
MyObject2{DataType}(Int16)

julia> Arrow.ArrowTypes.registertype!(MyObject2, MyObject2)

julia> tbl = (; obj = [MyObject2(Int16), MyObject2(Int16)])
(obj = MyObject2{DataType}[MyObject2{DataType}(Int16), MyObject2{DataType}(Int16)],)

julia> Arrow.write("test.arrow", tbl)
Unreachable reached at 0x7f529255f3f7

signal (4): Illegal instruction
in expression starting at REPL[11]:1
ToStruct at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:67
#45 at ./none:0
iterate at ./generator.jl:47 [inlined]
collect at ./array.jl:686 [inlined]
_totuple at ./tuple.jl:258 [inlined]
Tuple at ./tuple.jl:230 [inlined]
#arrowvector#44 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:89
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:81 [inlined]
#arrowvector#10 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:90
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:81
unknown function (ip: 0x7f5292560666)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#arrowvector#4 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:58
unknown function (ip: 0x7f529255f0f3)
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:52
unknown function (ip: 0x7f529255ed96)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#45 at ./none:0
iterate at ./generator.jl:47 [inlined]
collect_to! at ./array.jl:732
collect_to_with_first! at ./array.jl:710
unknown function (ip: 0x7f529255e99b)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
collect at ./array.jl:691
_totuple at ./tuple.jl:258 [inlined]
Tuple at ./tuple.jl:230 [inlined]
#arrowvector#44 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:89
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:81 [inlined]
#arrowvector#10 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:90
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:81
unknown function (ip: 0x7f529255a0d6)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#arrowvector#4 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:58
unknown function (ip: 0x7f5292558273)
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:52
unknown function (ip: 0x7f5292557f16)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#45 at ./none:0
iterate at ./generator.jl:47 [inlined]
collect at ./array.jl:686
_totuple at ./tuple.jl:258 [inlined]
Tuple at ./tuple.jl:230 [inlined]
#arrowvector#44 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:89
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:81 [inlined]
#arrowvector#10 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:90
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:81
unknown function (ip: 0x7f5292557b16)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#arrowvector#4 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:58
unknown function (ip: 0x7f5292555cb3)
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:52
unknown function (ip: 0x7f5292555956)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#45 at ./none:0
iterate at ./generator.jl:47 [inlined]
collect at ./array.jl:686
_totuple at ./tuple.jl:258 [inlined]
Tuple at ./tuple.jl:230 [inlined]
#arrowvector#44 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:89
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/struct.jl:81 [inlined]
#arrowvector#10 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:90
unknown function (ip: 0x7f529255556d)
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:81
unknown function (ip: 0x7f529255396d)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#arrowvector#4 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:58
unknown function (ip: 0x7f52925536bd)
arrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:52 [inlined]
#toarrowvector#3 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:36
toarrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:34 [inlined]
toarrowvector##kw at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/arraytypes/arraytypes.jl:34 [inlined]
#109 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:202
eachcolumn at /home/ec2-user/.julia/packages/Tables/8FVkV/src/utils.jl:70 [inlined]
toarrowtable at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:201
unknown function (ip: 0x7f5292553354)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
macro expansion at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:111 [inlined]
macro expansion at ./task.jl:332 [inlined]
write at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:108
#100 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:77 [inlined]
#open#287 at ./io.jl:325
open at ./io.jl:323 [inlined]
#write#99 at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:76 [inlined]
write at /home/ec2-user/.julia/packages/Arrow/Re9EM/src/write.jl:76
unknown function (ip: 0x7f529254ffda)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:566
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:790
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:790
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:790
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:883
eval at ./boot.jl:331
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
#run_repl#37 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#807 at ./client.jl:399
jfptr_YY.807_45002.clone_1 at /home/ec2-user/.asdf/installs/julia/1.5.3/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:705
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
run_main_repl at ./client.jl:383
exec_options at ./client.jl:313
_start at ./client.jl:506
jfptr__start_53898.clone_1 at /home/ec2-user/.asdf/installs/julia/1.5.3/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1690 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:106
main at /buildworker/worker/package_linux64/build/ui/repl.c:227
__libc_start_main at /lib64/libc.so.6 (unknown line)
_start at /home/ec2-user/.asdf/installs/julia/1.5.3/bin/julia (unknown line)
Allocations: 31191622 (Pool: 31182957; Big: 8665); GC: 34
zsh: illegal hardware instruction  julia --project=.
```

**Comment by quinnj** [comment] 2021-03-06 07:19
Duplicate of https://github.com/JuliaData/Arrow.jl/issues/74

**Comment by quinnj** [comment] 2021-03-06 07:20
(but thanks for the report! it's always helpful to hear of what people are running into)

**Closed by quinnj** 2021-03-06 07:19 UTC
